version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "NO TESTS"
      - deploy:
          name: "Deploy to server when on master"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan omnilogie.fr >> ~/.ssh/known_hosts
              git push dokku@omnilogie.fr:omnilogie master -f
            fi
